name: indent_string
description: Small dart util used to indent each line in a string.
version: 1.0.0
repository: https://github.com/mvitlov/indent_string
issue_tracker: https://github.com/mvitlov/indent_string/issues?q=is%3Aissue+is%3Aopen+


environment:
  sdk: ^3.2.6

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
